# backend/core/state.py

from typing import TypedDict, List, Dict, Any, Optional, Annotated
from langchain_core.messages import BaseMessage
import operator


class AgentState(TypedDict):
    
    # 1️⃣ Conversation History
    # All messages exchanged between user and system
    messages: Annotated[List[BaseMessage], operator.add]
    
    
    # 2️⃣ User Profile
    # Data retrieved from PostgreSQL
    user_profile: Dict[str, Any]
    
    
    # 3️⃣ Router Intent
    # Possible values:
    # "direct_info" → user asking scheme info
    # "eligibility_audit" → user wants eligibility check
    intent: Optional[str]
    
    
    # 4️⃣ Retrieved Schemes
    # Schemes fetched from Qdrant vector DB
    matched_schemes: List[Dict[str, Any]]
    
    
    # 5️⃣ Missing User Fields
    # Used by Interviewer agent to collect more info
    missing_fields: List[str]
    
    
    # 6️⃣ Eligibility Results
    # Example:
    # [
    #   {"scheme": "PMAY", "eligible": True, "reason": "..."},
    #   {"scheme": "Ayushman Bharat", "eligible": False, "reason": "..."}
    # ]
    eligibility_results: Optional[List[Dict[str, Any]]]
    
    
    # 7️⃣ Scheme Details
    # Used when user asks direct questions
    scheme_details: Optional[List[Dict[str, Any]]]
    
    
    # 8️⃣ Profile Completeness
    # Whether we have enough info to evaluate eligibility
    is_profile_complete: Optional[bool]
    
    
    # 9️⃣ Current Interview Question
    # Tracks what the interviewer asked last
    current_question: Optional[str]
    
    
    # 🔟 Final Response
    # Generated by the Clerk agent
    final_response: Optional[str]
    
    
    # 11️⃣ Debug Information
    # Helpful for logging / troubleshooting
    debug_info: Optional[Dict[str, Any]]

   
    response_mode: Optional[str]
    # Stores the specific scheme name for follow-ups
    selected_scheme: Optional[str]